### ISSUE TITLE
Undefined symbols for architecture x86_64:   "___isOSVersionAtLeast", referenced from:       -[TiIdentityModule biometryType]

### ISSUE THREAD

**Issue by marconealberto** [appcelerator-modules/titanium-identity#14]
This is the complete error:

```
Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      -[TiIdentityModule biometryType] in libti.identity.a(TiIdentityModule.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Can't compile it with Xcode 8.2.1 on an iOS 10, with Titanium SDK 6.3.0.
It works on Xcode 9.2 and iOS 11, same SDK.

**Comment by marconealberto** [comment]
this looks like a workaround at the moment for me:

https://forums.adobe.com/thread/2384080

**Comment by hansemannn** [comment]
Ti.Identity should be used on Xcode 9+ only, but I am fine removing it for now, until we bump the minimum SDK version to 7.0.0.

**Comment by hansemannn** [comment]
Fixed in [v1.0.4](https://github.com/appcelerator-modules/titanium-identity/releases/tag/ios-1.0.4).
